### ISSUE TITLE
建议将rua的头像改成圆的

### ISSUE THREAD

**Issue by Steven52065** [MeetWq/nonebot-plugin-petpet#10]
![806EABDB-956E-4640-9D9E-547785BBB37A](https://user-images.githubusercontent.com/36119581/152724985-d2f05664-87de-493e-bb6a-e2a221202b26.gif)

感觉rua一个方的有点奇怪…（另祝大佬新年快乐（好像有点晚了…

**Comment by MeetWq** [comment]
这个rua圆的我也见过，我反而觉得方的好一点...
我先放着，要是还有人觉得圆的好我在改（

**Comment by Steven52065** [comment]
> 这个rua圆的我也见过，我反而觉得方的好一点...
> 我先放着，要是还有人觉得圆的好我在改（

麻烦大佬了（南北！）

**Comment by jcjrobert** [comment]
其实我也觉得方的更好些，圆的有时候切割会莫名违和（
不然加个选项？（比如 摸头圆 这样

**Comment by leinlin** [comment]
我觉得⚪的好玩一些比较q

**Comment by MeetWq** [comment]
58a857c6450329ddc74d465fc64731bbda693a66 添加了“圆”选项，如 摸头圆 qq
