### ISSUE TITLE
强烈推荐新的表情包

### ISSUE THREAD

**Issue by 863109569** [MeetWq/nonebot-plugin-petpet#11]
![V{}C$9B@5$M2ITN`E_OZSHK](https://user-images.githubusercontent.com/77315378/153204166-0ee849f3-5b1b-4d54-9a24-7add837d6e1b.gif)
虽然好像有点难，但是拜托了（

**Comment by MeetWq** [comment]
有推荐的关键词吗（

**Comment by 863109569** [comment]
> 有推荐的关键词吗（

膜/膜拜

**Comment by 863109569** [comment]
> 有推荐的关键词吗（

膜/膜拜

**Comment by MeetWq** [comment]
加了
