### ISSUE TITLE
新表情 问问 出错

### ISSUE THREAD

**Issue by moian98** [MeetWq/nonebot-plugin-petpet#14]
nonebot后台提示：
`nonebot.adapters.onebot.v11.exception.ActionFailed: <ActionFailed data=None, echo={'seq': 12}, msg=SEND_MSG_API_ERROR, retcode=100, status=failed, wording=请参考 go-cqhttp 端输出>`

直接用pip下载的插件，未做任何修改。。。不知道是哪里的问题？

**Comment by moian98** [comment]
gocq这边是这个提示：
![image](https://user-images.githubusercontent.com/56097585/155508021-b0dc96de-fc2f-4050-8852-c6edb9e0521a.png)

**Comment by moian98** [comment]
再加一条：在群里使用 问问 + @群友 时没问题，使用自己手动提供的图片就出现上面的提示。

**Comment by MeetWq** [comment]
确实有问题
另外自己提供图片是需要加名字的，如：问问可莉 [图片]

**Comment by MeetWq** [comment]
> 确实有问题 另外自己提供图片是需要加名字的，如：问问可莉 [图片]

@群友 也可以加名字，不加的话会用群名片的名字
