### ISSUE TITLE
做图失败的时候block好像还是true?

### ISSUE THREAD

**Issue by 863109569** [MeetWq/nonebot-plugin-petpet#15]
虽然我看了代码，程序在失败的时候block为false,但是运行起来好像还是true

**Comment by MeetWq** [comment]
是指令不匹配的时候block为false，如果是失败了会回复出错了

**Comment by 863109569** [comment]
> 是指令不匹配的时候block为false，如果是失败了会回复出错了

那么就是不匹配的时候block好像还是true
![image](https://user-images.githubusercontent.com/77315378/156879434-54a7a22c-32f6-4eae-8741-17d8334b8058.png)
![BLD_EOXAW606$}3AEMJZLM9](https://user-images.githubusercontent.com/77315378/156879441-fa92fe3c-3f5e-4d82-91c1-b6fa21b4fa49.png)

**Comment by 863109569** [comment]
![image](https://user-images.githubusercontent.com/77315378/156879458-37cae998-b575-4878-859f-262c7324b5ad.png)

**Comment by MeetWq** [comment]
因为这个判断是写在handle里的，没有写在rule里，所以还是会进handle，但应该不影响后面优先级的matcher

**Comment by MeetWq** [comment]
在 cc08d0acde4eca70b4dbd61698a16722d5823b50 里改了
