### ISSUE TITLE
gif建议减帧压缩，比如我这个代码就是把帧数保持在 70帧，不压缩的gif非常大，发送回卡死服务器

### ISSUE THREAD

**Issue by leinlin** [MeetWq/nonebot-plugin-petpet#18]
frames = []
        shrinkTime = float(img.n_frames) / 70

        for i in range(img.n_frames):
            if shrinkTime > 1:
                if shrinkTime*i >= img.n_frames:
                    break
                img.seek(int(shrinkTime * i))
                frames.append(paste(img))
            else:
                img.seek(i)
                frames.append(paste(img))

        bg.close()
        img.close()

        duration = img.info["duration"]
        if shrinkTime > 1:
            duration = min(duration * shrinkTime, 280)

**Comment by MeetWq** [comment]
710204edae4328246db428d6966831615570eca5 里改了
