### ISSUE TITLE
继续干活下面空了一块实在太难看了，建议还是用长方形的，把图片的高度适配一下，然后宽度居中截取

### ISSUE THREAD

**Issue by leinlin** [MeetWq/nonebot-plugin-petpet#20]
![image](https://user-images.githubusercontent.com/30318270/157683661-7e552410-b587-461b-bb99-0172937c6591.png)

而且平常的照片也是长方形的啊....

![image](https://user-images.githubusercontent.com/30318270/157683801-f974795a-960c-4f10-8a85-9ec19743d729.png)

**Comment by MeetWq** [comment]
主要是找的这个模板有边框，不然直接一个整整齐齐的长方形会有些违和

**Comment by leinlin** [comment]
> 我可以把边框往下移一些

然后就是图片还是建议从上往下那样子的，不然没有人头了****

**Comment by MeetWq** [comment]
5cf4592c7431fbc969051c12320a2f073e5ca33d
