### ISSUE TITLE
建议警察证改成这样子的

### ISSUE THREAD

**Issue by leinlin** [MeetWq/nonebot-plugin-petpet#21]
![8L1SLITE4I7UHWV$FI5OQS1](https://user-images.githubusercontent.com/30318270/157685549-1878b2e7-c923-4fc3-a419-57ab68559973.png)
黑猫改成头像

**Comment by jcjrobert** [comment]
建议都要（x

**Comment by MeetWq** [comment]
我本来想要这种的，但这种不太合适（
![-542ba968dd945b51.jpg](https://s2.loli.net/2022/03/10/ApVPQLkO1bdTuMD.jpg)

**Comment by leinlin** [comment]
你这种的人头太难适配了，很难看然后警察帽子也没留着

**Comment by leinlin** [comment]
![image](https://user-images.githubusercontent.com/30318270/157691039-05e749ca-4359-49dd-8af6-b7125930c470.png)
我也想这样啊

**Comment by 3273576540** [comment]
但这个识图太容易失败了，有点帽子头发遮挡都找不到头

**Comment by MeetWq** [comment]
识图就太不可靠了，毕竟有人头像根本没有头（

**Comment by 3273576540** [comment]
确实所以这个没必要加进头像制作里，可以单独开个接头插件

**Comment by MeetWq** [comment]
132592b5b9d5cba6a1ca6798c7ae139506087308
