### ISSUE TITLE
撕的滑稽头其实可以改成自己的头像，这样子有助于群友们套娃

### ISSUE THREAD

**Issue by leinlin** [MeetWq/nonebot-plugin-petpet#22]
![image](https://user-images.githubusercontent.com/30318270/157686315-cd8eb967-f539-437a-9743-3158661ae0d8.png)

**Comment by MeetWq** [comment]
可以

**Comment by MeetWq** [comment]
ecc56d8396bd9ca3bdca25864eb38bfa59612f72
