### ISSUE TITLE
玩游戏建议能输入名字，比如来玩老头环啊

### ISSUE THREAD

**Issue by leinlin** [MeetWq/nonebot-plugin-petpet#23]
![JIV90OXQS6~I_M9KK)M%CRC](https://user-images.githubusercontent.com/30318270/157692686-98af595b-f36e-4860-8abe-dbaae813a141.PNG)
玩游戏建议能输入名字，比如来玩老头环啊

然后 老头环作为参数输入

**Comment by MeetWq** [comment]
这个 #19 里改了

**Comment by leinlin** [comment]
async def play_game(users: List[UserInfo], args: List[str] = [], **kwargs) -> BytesIO:
    img = users[0].img
    bg = await load_image("play_game/0.png")
    font = await load_font(DEFAULT_FONT, 35)

    def make(img: IMG) -> IMG:
        img = to_jpg(img)
        frame = Image.new("RGBA", bg.size, (255, 255, 255, 0))
        points = [(0, -9), (225, -10), (210, 195), (0, 210)]
        screen = rotate(perspective(fit_size(img, (220, 170)), points), 9)
        frame.paste(screen, (161, 100))
        frame.paste(bg, mask=bg)

        name = (args[0] if args else "") or users[0].name
        if not name:
            return "找不到名字，加上名字再试吧~"

        draw = ImageDraw.Draw(frame)
        draw.text(
            (150, 430),
            f"来玩{name}啊",
            font=font,
            fill="#000000",
            stroke_fill="#FFFFFF",
            stroke_width=2,
        )
        return frame

    if not getattr(img, "is_animated", False):
        return save_jpg(make(img))
    else:
        frames = []
        shrinkTime = float(img.n_frames) / 70

        for i in range(img.n_frames):
            if shrinkTime > 1:
                if shrinkTime*i >= img.n_frames:
                    break
                img.seek(int(shrinkTime * i))
                frames.append(make(img))
            else:
                img.seek(i)
                frames.append(make(img))

        duration = img.info["duration"]
        if shrinkTime > 1:
            duration = min(duration * shrinkTime, 280)
        return save_gif(frames, duration / 1000)

**Comment by leinlin** [comment]
![ZEL6}RF{~7T`X7MPHPKD }Y](https://user-images.githubusercontent.com/30318270/157703093-b34c62a1-9ee2-4577-973a-760a510a601c.PNG)
