### ISSUE TITLE
来玩游戏全屏的时候 是有锯齿黑边的，看起来像是原图的电脑边框抠图的时候没有用边缘模糊，建议模糊擦弄一下

### ISSUE THREAD

**Issue by leinlin** [MeetWq/nonebot-plugin-petpet#24]
![image](https://user-images.githubusercontent.com/30318270/157707253-c415932b-1d00-462b-803d-7e4eb78ff38a.png)

**Comment by jcjrobert** [comment]
我以前用opencv搓这个也有这问题，不知道怎么解决就坑了（）

**Comment by leinlin** [comment]
建议使用灰色

**Comment by MeetWq** [comment]
5c1d58ef49d2071682d6c82f6cf7bb63daa92db5 把背景改成了灰色
