### ISSUE TITLE
撕建议在头上加一句话嘲讽一下，同是建议头用 那个 拍拍的黑色遮罩把头切成椭圆更有立体感一些

### ISSUE THREAD

**Issue by leinlin** [MeetWq/nonebot-plugin-petpet#26]

**Comment by leinlin** [comment]
![VSR6NT_YN1UVAL0}Z4_YM(2](https://user-images.githubusercontent.com/30318270/157838448-f59fcb6b-618c-4df8-8ec8-05cfec50cb0c.PNG)

**Comment by leinlin** [comment]
![image](https://user-images.githubusercontent.com/30318270/157838646-ada1cc2a-12d1-4309-9e5c-d438d1206b8d.png)

**Comment by MeetWq** [comment]
@jcjrobert 要不要把“滑稽”选项去掉

**Comment by jcjrobert** [comment]
> 

可以判断开始有没有单独一个滑稽字段，然后截后面进行正常处理（就是得空格）

**Comment by leinlin** [comment]
async def rip(
    users: List[UserInfo], sender: UserInfo, args: List[str] = [], **kwargs
) -> BytesIO:
    if len(users) >= 2:
        self_img = users[0].img
        user_img = users[1].img
    else:
        self_img = sender.img
        user_img = users[0].img
    rip = await load_image("rip/0.png")
    frame = Image.new("RGBA", rip.size, (255, 255, 255, 0))
    left = rotate(resize(user_img, (385, 385)), 24)
    right = rotate(resize(user_img, (385, 385)), -11)
    frame.paste(left, (-5, 355))
    frame.paste(right, (649, 310))
    frame.paste(rip, mask=rip)
    if not (args and "滑稽" in args[0]):
        self_img = resize(circle(self_img), (215, 215))
        frame.paste(self_img, (408, 418), mask=self_img)

    if args:
        text = args[0].replace("滑稽", "")
        fontname = DEFAULT_FONT
        fontsize = await fit_font_size(text, rip.width, 300, fontname, 150, 25)
        if not fontsize:
            return "名字太长了哦，改短点再试吧~"
        font = await load_font(fontname, fontsize)
        text_w = font.getsize(text)[0]
        draw = ImageDraw.Draw(frame)
        draw.text(
            ((rip.width - text_w) / 2, 40),
            text,
            font=font,
            fill="#FF0000",
            stroke_width=2,
        )

    return save_jpg(frame)

**Comment by MeetWq** [comment]
753e8843ce45cbdd51e2096cbf2846970731ead0
