### ISSUE TITLE
我朋友说那里建议 replace ”他“ 的代码改成这样 replace “他是”

### ISSUE THREAD

**Issue by leinlin** [MeetWq/nonebot-plugin-petpet#29]
text = text.replace("他是", "我是").replace("她是", "我是").replace("它是", "我是")

不然这个会有问题：
我朋友说 还有吗？叫他多来点

变成 叫我多来点

**Comment by MeetWq** [comment]
这样不太行，比如 我朋友说他想康康 就不行了
我改成指替换开头吧

**Comment by leinlin** [comment]
直接说 我想看看然后撤回就好了，直接replace他 会让一些正常的表达不正常

**Comment by MeetWq** [comment]
那就不替换了
