### ISSUE TITLE
一些建议

### ISSUE THREAD

**Issue by jcjrobert** [MeetWq/nonebot-plugin-petpet#3]
首先感谢大佬开源，我提一些建议（
1.不支持at自己，解决方法是额外加上to_me判断即可
2.建议qq和url放到一个列表，然后按顺序load_image，接着make_image
（本意是因为部分图片制作功能不能随便指定两个人所以改了一下）
3.设置优先级会吞(

**Comment by MeetWq** [comment]
感谢建议
1 可以理解，我之后会加上去
2 我没太明白是什么意思，是指一次同时制作多张图片吗？
3 是指 on_command 的优先级吗？

**Comment by jcjrobert** [comment]
2是指可以放两张图片，然后都接收，你现在的插件只能做到接收一张，然后另一个是使用者，因为id和url分开会很乱所以不如放在一起，一次制作多张图片也算一个
3是on_command的优先级，是我自己的问题（（

**Comment by MeetWq** [comment]
已经更新了
1 可以@bot了
2 可以做到随便指定两个人了，如：亲 114514  123456
