### ISSUE TITLE
我朋友说能不能支持下换行，气泡要切成9块，然后先计算气泡的长度，然后draw换行的text

### ISSUE THREAD

**Issue by leinlin** [MeetWq/nonebot-plugin-petpet#31]

**Comment by jcjrobert** [comment]
甚至可以搞多个回复放在一起

**Comment by MeetWq** [comment]
目前效果如下，有多个参数的时候会认为第一个参数是名字

![RDV5C_SM1Z~W6_K@O5O0ZKG.jpg](https://s2.loli.net/2022/03/12/xa5X1e8cJfhQEyi.jpg)

**Comment by MeetWq** [comment]
单句话内换行需要用引号引起来

![1PFXFA@~GFC_0GL__EXZP52.jpg](https://s2.loli.net/2022/03/12/EUi34vqr7xVRlKB.jpg)
