### ISSUE TITLE
问问中间的那个图片可以改成 类似 鲁迅说的感觉，输入名字 和内容然后 说一些骚话

### ISSUE THREAD

**Issue by leinlin** [MeetWq/nonebot-plugin-petpet#32]
![image](https://user-images.githubusercontent.com/30318270/158010774-e89b0135-1d27-4ca5-808e-f825e6eb6f5e.png)

**Comment by jcjrobert** [comment]
可以定制三段文字，名字，中间的话，结论，甚至开头也能改，但是要定制的话，我的想法是不然全定制，不然就只接收名字

**Comment by leinlin** [comment]
> 可以定制三段文字，名字，中间的话，结论，甚至开头也能改，但是要定制的话，我的想法是不然全定制，不然就只接收名字

这个是原神的对话框，所以希望 能和原神有一个很相近的地方

**Comment by leinlin** [comment]
参数 两个被@的人，以及要说的话

**Comment by jcjrobert** [comment]
> 参数 两个被@的人，以及要说的话

所以为啥要at两个人，没懂，有例子么（
