### ISSUE TITLE
如果import cv2有问题的话会有哪些功能用不了呀...

### ISSUE THREAD

**Issue by InariInDream** [MeetWq/nonebot-plugin-petpet#43]
更新了下插件发现用不了了，找了下报错发现"from cv2 import *"的时候出错了，应该是服务器电脑上面缺dll，但是搞了半天也没解决...就找了最近一个没用cv2的版本开始用了....

**Comment by InariInDream** [comment]
> cv2是0.2.9加入的，之前的话从第32个表情开始就没法用了 你可以把报错贴上来，看看能不能解决

我是只把utils文件替换成了最新的无cv2的版本，发现有些新表情还是可以用的（比如陪睡券、听音乐、安全感这种）但是朋友说和对称确实用不了（

这是替换前的报错
![DVCN{T5K8CJ_IXGC@K5MDUT](https://user-images.githubusercontent.com/101713235/158715908-2f40b324-6cbd-4f3e-9370-3eae84be67c2.png)

用百度到的工具查了下 好像缺一堆dll文件？重装了好几个版本的cv2也无济于事 XD
然后也实在不想一个一个找来下载就放弃了......

![~OTL1WM_HXKHGI82DMDCEFD](https://user-images.githubusercontent.com/101713235/158716654-45307828-f6e5-484b-b50f-451472ccbafd.png)


朋友说和对称分别会提示这样的报错
![image](https://user-images.githubusercontent.com/101713235/158717164-b01bcf9f-e57e-4c90-9576-4e33f50ae5de.png)
![image](https://user-images.githubusercontent.com/101713235/158717187-3fc7d8ae-b8cd-4f4e-b497-d1448c5f206e.png)


应该是我服务器电脑上自己配置的问题...就不麻烦作者辽，大部分是能够正常使用的

**Comment by MeetWq** [comment]
https://pypi.org/project/opencv-python/
看 Frequently Asked Questions 部分

**Comment by InariInDream** [comment]
感谢感谢！在服务器上面安装了一个叫桌面体验的东西重启之后就解决了
![image](https://user-images.githubusercontent.com/101713235/158753819-71173505-f1d6-41ee-85e8-bd7b4f0e93e4.png)
我的是windows server2012  据说windows server2019不会出现这个问题？
