### ISSUE TITLE
服务器挂了代理会图片下载出错

### ISSUE THREAD

**Issue by jx9468** [MeetWq/nonebot-plugin-petpet#47]
试了好几次发现服务器挂了VPN后  摸[图片]  等会显示'图片下载出错，请稍后再试'，但摸@qq 和 摸 qq号可以正常使用。所有的指令+图片都会失败。希望可以加个代理配置🤣

**Comment by MeetWq** [comment]
不应该是这边加代理配置吧🤣

建议别开全局代理，需要代理的插件加代理配置
