### ISSUE TITLE
插件成功加载却无法使用。。。

### ISSUE THREAD

**Issue by moian98** [MeetWq/nonebot-plugin-petpet#9]
使用`pip install nonebot-plugin-petpet`安装后，插件也成功加载了。
![QQ截图20220128172242](https://user-images.githubusercontent.com/56097585/151520948-88afce65-9801-4ac2-a5f2-b31c1b909d8d.png)
但却无法使用，在群里输入指令后无法返回消息。
![eor](https://user-images.githubusercontent.com/56097585/151521217-219a75a2-2a29-46f7-907e-f27571f65baa.png)
请问怎么回事呀？

**Comment by MeetWq** [comment]
如果没有改过 `COMMAND_START` 的话，命令要以 `/` 开头，比如 `/亲 自己`

**Comment by moian98** [comment]
一样试过，都不行
![Uploading eor.png…]()

**Comment by MeetWq** [comment]
你的 `nonebot_repeat` 是怎么写的？我看它的优先级是 1，如果你设置的是 `block=True` 的话，后面优先级的插件都不会执行了

建议去掉 `nonebot_repeat` 再试试

**Comment by moian98** [comment]
这是我的nonebot_repeat源代码
`# -*- coding: utf-8 -*-
from nonebot.plugin import on_message
from nonebot.adapters import Bot
from nonebot.adapters.onebot.v11 import GroupMessageEvent


wake = on_message()


@wake.handle()
async def _(bot: Bot, event: GroupMessageEvent):
    group = event.group_id
    # 云悠悠
    if group == 960606905:
        msg = event.get_message()
        await bot.send_guild_channel_msg(guild_id=64367701640535246, channel_id=2644556, message=msg)
    # 星瞳
    if group == 958614882:
        msg = event.get_message()
        await bot.send_guild_channel_msg(guild_id=64367701640535246, channel_id=2253161, message=msg)`

帮我看看吧，我不知道在哪里修改优先级。谢谢了。

**Comment by moian98** [comment]
我试着移除了我的repeat，确实没问题了。。。确实是我的代码的问题。。。但我不知道怎么设置优先级。help me，谢谢。

**Comment by moian98** [comment]
已经解决了。谢谢！

**Comment by moian98** [comment]
已经解决了，谢谢！
